In [4]:
import pandas as pd
import gmaps
import requests

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [5]:
file = "./Resources/listings_cleaned2.csv"

In [6]:
region_df = pd.read_csv(file)
region_df.head()

,id,host_since,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,zipcode,...,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_days_active,time_since_first_review,time_since_last_review
0,958,7/31/2008,within a few hours,100%,1,1,1,1,Western Addition,94115,...,9.0,1,1,1,0,0,1.60,3958,4+ years,17
1,7918,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,94117,...,8.0,0,9,0,9,0,0.14,3637,4+ years,923
2,8142,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,94117,...,9.0,0,9,0,9,0,0.14,3637,4+ years,263
3,8339,7/2/2009,within an hour,100%,0,2,2,1,Western Addition,94115,...,9.0,0,2,2,0,0,0.23,3622,4+ years,295
4,8739,1/27/2009,within an hour,100%,1,2,2,0,Mission,94110,...,10.0,1,2,0,2,0,5.61,3778,4+ years,12

In [7]:
region_df.dtypes

id                                                int64
host_since                                       object
host_response_time                               object
host_response_rate                               object
host_is_superhost                                 int64
host_listings_count                               int64
host_total_listings_count                         int64
host_identity_verified                            int64
neighbourhood_cleansed                           object
zipcode                                           int64
latitude                                        float64
longitude                                       float64
property_type                                    object
room_type                                        object
accommodates                                      int64
bathrooms                                       float64
bedrooms                                          int64
beds                                              int64
price                                             int64
minimum_nights                                    int64
maximum_nights                                    int64
calendar_updated                                 object
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
first_review                                     object
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
instant_bookable                                  int64
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
host_days_active                                  int64
time_since_first_review                          object
time_since_last_review                            int64
dtype: object

In [8]:
# Filter hosts and
clean_df = region_df.loc[(region_df["host_response_rate"] == '100%') & 
                        (region_df['host_is_superhost'] == 1) &
                        (region_df['host_identity_verified'] == 1) &
                        (region_df['instant_bookable'] == 1) & 
                        # review ratings.
                        (region_df['review_scores_rating'] >= 80) & 
                        (region_df['review_scores_accuracy'] >= 7) & 
                        (region_df['review_scores_cleanliness'] >= 7) & 
                        (region_df['review_scores_checkin'] >= 7) & 
                        (region_df['review_scores_communication'] >= 7) & 
                        (region_df['review_scores_location'] >= 7) & 
                        (region_df['review_scores_value'] >= 7) &
                        # recent calendar updates.
                        (region_df['calendar_updated'] != '17 months ago') &
                        (region_df['calendar_updated'] != '14 months ago') &
                        (region_df['calendar_updated'] != '12 months ago')]
clean_df

,id,host_since,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,zipcode,...,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_days_active,time_since_first_review,time_since_last_review
0,958,7/31/2008,within a few hours,100%,1,1,1,1,Western Addition,94115,...,9.0,1,1,1,0,0,1.60,3958,4+ years,17
11,12522,5/22/2009,within an hour,100%,1,1,1,1,Castro/Upper Market,94110,...,10.0,1,1,0,1,0,3.48,3663,4+ years,18
18,23611,5/25/2009,within an hour,100%,1,3,3,1,Bernal Heights,94110,...,10.0,1,2,1,1,0,2.17,3660,4+ years,9
48,51557,9/16/2010,within an hour,100%,1,1,1,1,Western Addition,94115,...,10.0,1,1,1,0,0,1.00,3181,4+ years,78
58,59702,11/14/2010,within an hour,100%,1,1,1,1,Bernal Heights,94110,...,10.0,1,1,0,1,0,1.93,3122,4+ years,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4924,32744842,5/5/2014,within an hour,100%,1,1,1,1,Outer Richmond,94121,...,10.0,1,1,1,0,0,1.70,1854,0-6 months,41
4925,32746244,6/14/2014,within an hour,100%,1,1,1,1,Outer Richmond,94121,...,10.0,1,1,1,0,0,7.76,1814,0-6 months,2
4963,33166972,2/15/2012,within an hour,100%,1,4,4,1,Castro/Upper Market,94110,...,10.0,1,4,1,2,1,12.35,2664,0-6 months,3
5012,34056383,7/8/2011,within an hour,100%,1,2,2,1,Outer Sunset,94132,...,10.0,1,2,2,0,0,1.00,2886,0-6 months,16
5037,34477166,10/5/2012,within an hour,100%,1,5,5,1,Castro/Upper Market,94110,...,10.0,1,1,1,0,0,6.00,2431,0-6 months,2

In [9]:
clean_df.calendar_updated.value_counts()

today            108
2 weeks ago       86
3 weeks ago       37
a week ago        35
4 days ago        27
yesterday         26
4 weeks ago       24
2 months ago      21
5 days ago        19
3 days ago        19
5 weeks ago       19
6 days ago        13
6 weeks ago       12
7 weeks ago       12
2 days ago        10
1 week ago         9
3 months ago       7
7 months ago       3
4 months ago       3
10 months ago      2
5 months ago       2
11 months ago      1
8 months ago       1
6 months ago       1
Name: calendar_updated, dtype: int64

In [10]:
# Ask the customer to add a minimum and maximum price value.
min_price = float(input("What is the minimum price you would like for your hotel? "))
max_price = float(input("What is the maximum price you would like for your hotel? "))

What is the minimum price you would like for your hotel? 10
What is the maximum price you would like for your hotel? 100

In [11]:
# Filter the dataset to find the hotels that fit the criteria.
preferred_df = clean_df.loc[(clean_df["price"] <= max_price) & (clean_df["price"] >= min_price)]
preferred_df

,id,host_since,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,zipcode,...,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_days_active,time_since_first_review,time_since_last_review
11,12522,5/22/2009,within an hour,100%,1,1,1,1,Castro/Upper Market,94110,...,10.0,1,1,0,1,0,3.48,3663,4+ years,18
18,23611,5/25/2009,within an hour,100%,1,3,3,1,Bernal Heights,94110,...,10.0,1,2,1,1,0,2.17,3660,4+ years,9
135,208727,4/19/2011,within an hour,100%,1,8,8,1,Outer Richmond,94121,...,9.0,1,2,0,2,0,0.33,2966,4+ years,265
157,256176,8/16/2011,within an hour,100%,1,1,1,1,Inner Richmond,94118,...,9.0,1,1,0,1,0,3.12,2847,4+ years,4
189,323635,7/12/2011,within an hour,100%,1,2,2,1,Excelsior,94134,...,10.0,1,2,0,2,0,0.71,2882,4+ years,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4713,31206489,9/11/2014,within an hour,100%,1,3,3,1,Noe Valley,94114,...,10.0,1,3,0,3,0,6.27,1725,0-6 months,4
4762,31595144,4/3/2012,within an hour,100%,1,4,4,1,Bernal Heights,94110,...,10.0,1,4,1,3,0,5.82,2616,0-6 months,1
4835,32210241,1/29/2012,within an hour,100%,1,4,4,1,Pacific Heights,94115,...,10.0,1,3,1,2,0,2.06,2681,0-6 months,20
4894,32617586,3/4/2013,within an hour,100%,1,6,6,1,Mission,94110,...,10.0,1,5,0,5,0,1.38,2281,0-6 months,28
4918,32724526,9/20/2014,within an hour,100%,1,1,1,1,Glen Park,94131,...,10.0,1,1,1,0,0,5.29,1716,0-6 months,10

In [12]:
# Create a descirption box.
info_box_template = """
<dl>
<dt>ID</dt><dd>{id}</dd>
<dt>Neighbourhood</dt><dd>{neighbourhood_cleansed}</dd>
<dt>Price</dt><dd>{price}</dd>
<dt>Rating</dt><dd>{review_scores_rating}</dd>
</dl>
"""

# Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in preferred_df.iterrows()]

# Get the latitude and longitude from each row and store in a new DataFrame.
locations = preferred_df[["latitude", "longitude"]]

In [13]:
# Assign the figure variable.
fig = gmaps.figure(center=(37.77, -122.4), zoom_level=11.8)

# Add a marker_layer.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Display.
fig

Figure(layout=FigureLayout(height='420px'))